name: Publish artifact

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  publish-artifact:
    permissions:
      packages: write
      contents: read
    name: Build and publish artifact to ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create m2-settings
        uses: whelk-io/maven-settings-xml-action@9dc09b23833fa9aa7f27b63db287951856f3433d # v22
        with:
          repositories: '[
            { "id": "github", "url": "https://maven.pkg.github.com/navikt/maven-release", "releases": { "enabled": "true" }, "snapshots": { "enabled": "false" } },
            { "id": "confluent", "url": "https://packages.confluent.io/maven/" }
          ]'
          servers: '[
            { "id": "github", "username": "x-access-token", "password": "${{ secrets.READER_TOKEN }}" },
            { "id": "ghcr", "username": "${{ github.actor }}", "password": "${{ secrets.GITHUB_TOKEN }}" }
          ]'
          output_file: settings.xml
      - name: Set up JDK${{ inputs.java-version }} and cache dependencies
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
          cache: 'maven'

      - name: Set release tag
        run: |
          echo "Setting tag ${{ github.ref_name }}"
          mvn --batch-mode versions:set -DnewVersion="${{ github.ref_name }}"
          mvn versions:commit
      - name: Build with Maven
        run: mvn --batch-mode --settings settings.xml deploy -DdeployAtEnd=true -DretryFailedDeploymentCount=3
